CREATE DATABASE IF NOT EXISTS todo_app;
USE todo_app;

CREATE TABLE IF NOT EXISTS todo_tasks (
    Id INT PRIMARY KEY,
    Task VARCHAR(255) NOT NULL,
    Created DATE NOT NULL,
    Completed BOOLEAN DEFAULT 0 NOT NULL
);
