CREATE DATABASE IF NOT EXISTS todo_tasks;
USE todo_tasks;

CREATE TABLE IF NOT EXISTS tasks (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Description VARCHAR(255) NOT NULL,
    Completed BOOLEAN NOT NULL
);
